default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml

      - id: check-json
        exclude: ^\.vscode/

      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.2
    hooks:
      - id: ruff-check
        name: "Ruff linter"
        args: ["--fix"]

      - id: ruff-format
        name: "Ruff formatter"

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.69
    hooks:
      - id: ty
        name: "ty type checking"

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.3
    hooks:
      - id: uv-lock
        name: "Ensure uv.lock is up to date"

      - id: uv-export
        name: "Generate the requirements.txt file"
        stages: [pre-push]

      - id: uv-audit
        name: "Audit dependencies"
        stages: [pre-push]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
        name: "Detect secrets"

  - repo: local
    hooks:
      - id: pytest
        name: "Run test suite"
        entry: make test
        language: system
        pass_filenames: false
        stages: [pre-push]
